### ISSUE TITLE
invalid config error

### ISSUE THREAD

**Issue by Abdelmounaim18** [dynasticorpheus/gigasetelements-ha#1]
Hi,

I was trying to setup this integration in Home Assistant, but unfortunately it wasn't working.
In the attached screenshots you can see my configuration and logs. I used HACS to install the add-on and checked if the files are in custom_components.  I hope you could help me out!

thnx in advance

---

<img width="985" alt="Schermafbeelding 2020-06-08 om 16 57 33" src="https://user-images.githubusercontent.com/44317217/84046340-424b7f80-a9aa-11ea-9ee8-f43425085102.png">
---
<img width="272" alt="Schermafbeelding 2020-06-08 om 16 52 31" src="https://user-images.githubusercontent.com/44317217/84046347-44add980-a9aa-11ea-9cb3-7eb12bad66fb.png">
---
<img width="452" alt="Schermafbeelding 2020-06-08 om 16 51 24" src="https://user-images.githubusercontent.com/44317217/84046348-45467000-a9aa-11ea-93ce-cee5e468604e.png">

**Comment by dynasticorpheus** [comment]
You only need to enter your information in configuration.yaml (and without **sensor:** )

**Comment by Abdelmounaim18** [comment]
Thnx, It is working now! Also, is it possible to integrate the motion and doorsensors in Home Assistant? That would be amazing.

**Comment by dynasticorpheus** [comment]
@Abdelmounaim18  That's definitely on the top of the to do list!

**Comment by ycardon** [comment]
Hi @dynasticorpheus, I did a port in node of your work on the cli, then it became a HA plugin. It's [here](https://github.com/ycardon/gigaset-elements-proxy). The project is working fine but it's a little complicated in term of integration: having a direct python integration like you do is better I think.

If you plan to integrate the different sensors of the ecosystem, you can have a look of the event list that we gathered.

**Comment by ycardon** [comment]
Last thing, I also had troubles with the configuration. Yaml syntax was incorrect with the README.md instructions. The following was working for me (in `configuration.yml`)

```yaml
# Gigaset elements alarm (https://github.com/dynasticorpheus/gigasetelements-ha)
gigasetelements:
  name: gigasetelements-alarm
  username: !secret gigasetelements_username
  password: !secret gigasetelements_password
```
