### ISSUE TITLE
alarm mode

### ISSUE THREAD

**Issue by lucaferrucci** [dynasticorpheus/gigasetelements-ha#25]
hello and thank you very much for your work.
Everything works perfectly, but I wanted to ask you if there is a way to intercept the state of the gigaset element in the alarm phase.
I would need it to activate automations during a possible break-in at the house.
I didn't understand if the alarm phase corresponds to the "panicmode" or is it another "state"

**Comment by dynasticorpheus** [comment]
Hi @lucaferrucci  Thanks!

Your alarm panel will have state **_triggered_** until alarm is dismissed. Panic switch will manually trigger the siren (alarm sound) in case you have that piece of hardware available in your setup.

Simple automation to put on light when alarm is triggered after sunset:

```
description: Turn on light when alarm is triggered after sunset
mode: single
trigger:
  - platform: state
    entity_id:
      - alarm_control_panel.gigaset_elements
    to: triggered
condition:
  - condition: sun
    after: sunset
action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.mini_smart_light_bulb

```
