### ISSUE TITLE
Arm Modes

### ISSUE THREAD

**Issue by swissmaster1** [dynasticorpheus/gigasetelements-ha#3]
Hi first of all I want to thank you for this nice plugin. I waited a long time on something like this.
I have a question according the alarm modes.
I set the switches up in ui-lovelace.yaml like this:
```
      - type: alarm-panel
        name: Gigaset Elements
        entity: alarm_control_panel.gigaset_elements
        states:
        - arm_home
        - arm_away
        - arm_night
```
Everthing is working and three buttons where shown Home, Away and Night. But when Home mode is actived nothing is shown in the panel. When I press the arm Home mode button then the mode in Gigaset Elements app switches to the individual mode and not to the Home mode. But the panel shows then correctly that a mode is activated. For me this is a strange behaviour. I'm not sure if I was able to describe it well. 
It would be nice when Home mode would be marked as activated if it is so. If something else is activated it would be nice when a click on Activate Home Mode will activate Home Mode and not individual Mode.

Last but not least I wanted to ask if there is a way to include a code panel (insert code for change alarm mode)?
